export const STAGE_SET = 'STAGE_SET';
export const STAGE_FINISH = 'STAGE_FINISH';
export const STAGE_ERROR = 'STAGE_ERROR';

export const QUESTIONS_FETCH_START = 'QUESTIONS_FETCH_START';
export const QUESTIONS_FETCH_SUCCESS = 'QUESTIONS_FETCH_SUCCESS';
export const QUESTIONS_FETCH_FAIL = 'QUESTIONS_FETCH_FAIL';
export const QUESTIONS_POINTER_SET = 'QUESTIONS_POINTER_SET'

export const USER_REGISTER = 'USER_REGISTER'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const SCORE_ADD = 'SCORE_ADD'
export const SCORE_RESET = 'SCORE_RESET'